### ISSUE TITLE
[Research] Find a NPM Package that will generate a PDF

### ISSUE THREAD

**Issue by davidholyko** [luchadko/resio#18]
### Timeline

* Successful Duration: 60 minutes
* Realistic Duration: 2 hours

### Required

* Must link Pull Request to related Github Issue
* Must have commit in the form of a semantic commit

### Acceptance Criteria

* None!

### Instructions (Optional)

* Find an NPM Package
* Comment in this issue with the Package

**Comment by lucaspchartier** [comment]
Installed `react-pdf` dependency
