### ISSUE TITLE
[Chore] Use npx create-react-app template

### ISSUE THREAD

**Issue by davidholyko** [luchadko/resio#2]
Timeline:

* Expected Duration: 10-30 minutes
* Allowed Duration: 2 hours

Acceptance Criteria:

* Must be a clean repo made from `npx create-react-app`

Instructions:

* delete local `resio` folder and all contents
* create new repo `npx create-react-app resio`
* link local folder to this repo 
* add, commit, and force push to master to overwrite

**Comment by lucaspchartier** [comment]
- deleted local resio folder and all contents
- created new repo npx create-react-app resio
- linked local folder to this repo
- added, commited, and forced push to master to overwrite

**Comment by lucaspchartier** [comment]
Reused npx-create-react-app template after updating Node to v.13.7.0 via Homebrew.
